"""agregar modelo Actor y tabla intermedia pelicula_actor

Revision ID: 0a7adfe575d1
Revises: d2257493a637
Create Date: 2026-08-11 17:04:57.031147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a7adfe575d1'
down_revision: Union[str, Sequence[str], None] = 'd2257493a637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('pais', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actores_id'), 'actores', ['id'], unique=False)
    op.create_table('pelicula_actor',
    sa.Column('pelicula_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actores.id'], ),
    sa.ForeignKeyConstraint(['pelicula_id'], ['peliculas.id'], )
    )
    op.drop_index(op.f('ix_reseñas_id'), table_name='reseñas')
    op.drop_table('reseñas')
    op.drop_index(op.f('ix_libros_id'), table_name='libros')
    op.drop_table('libros')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libros',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('autor', sa.VARCHAR(length=50), nullable=False),
    sa.Column('precio', sa.FLOAT(), nullable=False),
    sa.Column('disponible', sa.BOOLEAN(), nullable=True),
    sa.Column('año_publicacion', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_libros_id'), 'libros', ['id'], unique=False)
    op.create_table('reseñas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('texto', sa.VARCHAR(length=500), nullable=False),
    sa.Column('puntuacion', sa.INTEGER(), nullable=False),
    sa.Column('pelicula_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pelicula_id'], ['peliculas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reseñas_id'), 'reseñas', ['id'], unique=False)
    op.drop_table('pelicula_actor')
    op.drop_index(op.f('ix_actores_id'), table_name='actores')
    op.drop_table('actores')
    # ### end Alembic commands ###
