"""agregar año publicacion

Revision ID: 450e7469996b
Revises: 173212d6f533
Create Date: 2026-07-06 21:01:04.167509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '450e7469996b'
down_revision: Union[str, Sequence[str], None] = '173212d6f533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libros', sa.Column('año_publicacion', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('libros', 'año_publicacion')
    # ### end Alembic commands ###
