"""agregar modelo Actor y tabla intermedia pelicula_actor

Revision ID: bbb0e8818097
Revises: 0a7adfe575d1
Create Date: 2026-08-11 19:25:07.300017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb0e8818097'
down_revision: Union[str, Sequence[str], None] = '0a7adfe575d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reseña_id'), table_name='reseña')
    op.drop_table('reseña')
    op.add_column('actores', sa.Column('nombre', sa.String(length=50), nullable=False))
    op.add_column('actores', sa.Column('apellido', sa.String(length=50), nullable=False))
    op.drop_column('actores', 'name')
    op.drop_column('actores', 'lastname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actores', sa.Column('lastname', sa.VARCHAR(length=50), nullable=False))
    op.add_column('actores', sa.Column('name', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('actores', 'apellido')
    op.drop_column('actores', 'nombre')
    op.create_table('reseña',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('texto', sa.VARCHAR(length=500), nullable=False),
    sa.Column('puntuacion', sa.INTEGER(), nullable=False),
    sa.Column('pelicula_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pelicula_id'], ['peliculas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reseña_id'), 'reseña', ['id'], unique=False)
    # ### end Alembic commands ###
